language: node_js
node_js: stable
before_install:
  - openssl aes-256-cbc -K $encrypted_bc1057678923_key -iv $encrypted_bc1057678923_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - npm i
script:
  - npm run build
after_success:
  - ssh -o StrictHostKeyChecking=no root@$remote_host 'rm -rf /home/electronic-book/public'
  - scp -o stricthostkeychecking=no -r -v public root@$remote_host:/home/electronic-book/public
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - caandoll@aliyun.com
    on_success: always
    on_failure: always
